In [26]:
import os
import numpy as np
import pandas as pd

root = "/data/kaushal/FragBERTa"
file_dir = os.path.join(root, "data", "finetune", "raw")
out_dir = os.path.join(root, "data", "finetune", "interim")
os.makedirs(out_dir, exist_ok=True)

## BACE

In [2]:
df = pd.read_csv(os.path.join(file_dir, "bace.csv"))
df.head(2)

,mol,CID,Class,Model,pIC50,MW,AlogP,HBA,HBD,RB,...,PEOE6 (PEOE6),PEOE7 (PEOE7),PEOE8 (PEOE8),PEOE9 (PEOE9),PEOE10 (PEOE10),PEOE11 (PEOE11),PEOE12 (PEOE12),PEOE13 (PEOE13),PEOE14 (PEOE14),canvasUID
0,O1CC[C@@H](NC(=O)[C@@H](Cc2cc3cc(ccc3nc2N)-c2c...,BACE_1,1,Train,9.154901,431.56979,4.4014,3,2,5,...,53.205711,78.640335,226.85541,107.43491,37.133846,0.00000,7.980170,0.0,0.000000,1
1,Fc1cc(cc(F)c1)C[C@H](NC(=O)[C@@H](N1CC[C@](NC(...,BACE_2,1,Train,8.853872,657.81073,2.6412,5,4,16,...,73.817162,47.171600,365.67694,174.07675,34.923889,7.98017,24.148668,0.0,24.663788,2

In [3]:
df["Class"].value_counts()

Class
0    822
1    691
Name: count, dtype: int64

In [4]:
dg = pd.DataFrame({'smiles':df['mol'].values, 'Class':df['Class'].values})
dg.to_csv(os.path.join(out_dir, "bace.csv"), index=False, header=True, encoding="utf8")

## BBBP

In [5]:
df = pd.read_csv(os.path.join(file_dir, "bbbp.csv"))
df.head(2)

   num                  name  p_np                                    smiles
0    1            Propanolol     1          [Cl].CC(C)NCC(O)COc1cccc2ccccc12
1    2  Terbutylchlorambucil     1  C(=O)(OC(C)(C)C)CCCc1ccc(cc1)N(CCCl)CCCl

In [6]:
df["p_np"].value_counts()

p_np
1    1567
0     483
Name: count, dtype: int64

In [7]:
dg = pd.DataFrame({'smiles':df['smiles'].values, 'p_np':df['p_np'].values})
dg.to_csv(os.path.join(out_dir, "bbbp.csv"), index=False, header=True, encoding="utf8")

## HIV

In [8]:
df = pd.read_csv(os.path.join(file_dir, "hiv.csv"))
df.head(2)

                                              smiles activity  HIV_active
0  CCC1=[O+][Cu-3]2([O+]=C(CC)C1)[O+]=C(CC)CC(CC)...       CI           0
1  C(=Cc1ccccc1)C1=[O+][Cu-3]2([O+]=C(C=Cc3ccccc3...       CI           0

In [9]:
df["HIV_active"].value_counts()

HIV_active
0    39684
1     1443
Name: count, dtype: int64

In [10]:
dg = pd.DataFrame({'smiles':df['smiles'].values, 'HIV_active':df['HIV_active'].values})
dg.to_csv(os.path.join(out_dir, "hiv.csv"), index=False, header=True, encoding="utf8")

## SIDER

In [11]:
df = pd.read_csv(os.path.join(file_dir, "sider.csv"))
df.head(2)

,smiles,Hepatobiliary disorders,Metabolism and nutrition disorders,Product issues,Eye disorders,Investigations,Musculoskeletal and connective tissue disorders,Gastrointestinal disorders,Social circumstances,Immune system disorders,...,"Congenital, familial and genetic disorders",Infections and infestations,"Respiratory, thoracic and mediastinal disorders",Psychiatric disorders,Renal and urinary disorders,"Pregnancy, puerperium and perinatal conditions",Ear and labyrinth disorders,Cardiac disorders,Nervous system disorders,"Injury, poisoning and procedural complications"
0,C(CNCCNCCNCCN)N,1,1,0,0,1,1,1,0,0,...,0,0,1,1,0,0,1,1,1,0
1,CC(C)(C)C1=CC(=C(C=C1NC(=O)C2=CNC3=CC=CC=C3C2=...,0,1,0,0,1,1,1,0,0,...,0,1,1,0,0,0,1,0,1,0

In [12]:
df.columns

Index(['smiles', 'Hepatobiliary disorders',
       'Metabolism and nutrition disorders', 'Product issues', 'Eye disorders',
       'Investigations', 'Musculoskeletal and connective tissue disorders',
       'Gastrointestinal disorders', 'Social circumstances',
       'Immune system disorders', 'Reproductive system and breast disorders',
       'Neoplasms benign, malignant and unspecified (incl cysts and polyps)',
       'General disorders and administration site conditions',
       'Endocrine disorders', 'Surgical and medical procedures',
       'Vascular disorders', 'Blood and lymphatic system disorders',
       'Skin and subcutaneous tissue disorders',
       'Congenital, familial and genetic disorders',
       'Infections and infestations',
       'Respiratory, thoracic and mediastinal disorders',
       'Psychiatric disorders', 'Renal and urinary disorders',
       'Pregnancy, puerperium and perinatal conditions',
       'Ear and labyrinth disorders', 'Cardiac disorders',
       'Nervous system disorders',
       'Injury, poisoning and procedural complications'],
      dtype='object')

In [13]:
dg = df.copy(deep=True)
dg.to_csv(os.path.join(out_dir, "sider.csv"), index=False, header=True, encoding="utf8")

## TOX21

In [14]:
df = pd.read_csv(os.path.join(file_dir, "tox21.csv"))
df.head(2)

,NR-AR,NR-AR-LBD,NR-AhR,NR-Aromatase,NR-ER,NR-ER-LBD,NR-PPAR-gamma,SR-ARE,SR-ATAD5,SR-HSE,SR-MMP,SR-p53,mol_id,smiles
0,0.0,0.0,1.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,TOX3021,CCOc1ccc2nc(S(N)(=O)=O)sc2c1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,TOX3020,CCN1C(=O)NC(c2ccccc2)C1=O

In [15]:
df.columns

Index(['NR-AR', 'NR-AR-LBD', 'NR-AhR', 'NR-Aromatase', 'NR-ER', 'NR-ER-LBD',
       'NR-PPAR-gamma', 'SR-ARE', 'SR-ATAD5', 'SR-HSE', 'SR-MMP', 'SR-p53',
       'mol_id', 'smiles'],
      dtype='object')

In [16]:
dg = df.drop(columns=['mol_id'])
dg = dg[[dg.columns[-1]] + list(dg.columns[:-1])]
dg

,smiles,NR-AR,NR-AR-LBD,NR-AhR,NR-Aromatase,NR-ER,NR-ER-LBD,NR-PPAR-gamma,SR-ARE,SR-ATAD5,SR-HSE,SR-MMP,SR-p53
0,CCOc1ccc2nc(S(N)(=O)=O)sc2c1,0.0,0.0,1.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,CCN1C(=O)NC(c2ccccc2)C1=O,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0
2,CC[C@]1(O)CC[C@H]2[C@@H]3CCC4=CCCC[C@@H]4[C@H]...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN
3,CCCN(CC)C(CC)C(=O)Nc1c(C)cccc1C,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0
4,CC(O)(P(=O)(O)O)P(=O)(O)O,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7826,CCOc1nc2cccc(C(=O)O)c2n1Cc1ccc(-c2ccccc2-c2nnn...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN
7827,CC(=O)[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(...,1.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,0.0,NaN,0.0
7828,C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@@]43C)[C...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
7829,C[C@]12CC[C@@H]3c4ccc(O)cc4CC[C@H]3[C@@H]1CC[C...,1.0,1.0,0.0,NaN,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
7830,COc1ccc2c(c1OC)CN1CCc3cc4c(cc3C1C2)OCO4,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [17]:
dg.to_csv(os.path.join(out_dir, "tox21.csv"), index=False, header=True, encoding="utf8")

## ESOL

In [18]:
df = pd.read_csv(os.path.join(file_dir, "esol.csv"))
df.head(2)

,Compound ID,ESOL predicted log solubility in mols per litre,Minimum Degree,Molecular Weight,Number of H-Bond Donors,Number of Rings,Number of Rotatable Bonds,Polar Surface Area,measured log solubility in mols per litre,smiles
0,Amigdalin,-0.974,1,457.432,7,3,7,202.32,-0.77,OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)...
1,Fenfuram,-2.885,1,201.225,1,2,2,42.24,-3.30,Cc1occc1C(=O)Nc2ccccc2

In [19]:
dg = pd.DataFrame({'smiles':df['smiles'].values, 'measured log solubility in mols per litre':df['measured log solubility in mols per litre'].values})
dg.to_csv(os.path.join(out_dir, "esol.csv"), index=False, header=True, encoding="utf8")

## FREESOLV

In [20]:
df = pd.read_csv(os.path.join(file_dir, "freesolv.csv"))
df.head(5)

                              iupac                  smiles   expt   calc
0  4-methoxy-N,N-dimethyl-benzamide  CN(C)C(=O)c1ccc(cc1)OC -11.01 -9.625
1          methanesulfonyl chloride            CS(=O)(=O)Cl  -4.87 -6.219
2                 3-methylbut-1-ene                CC(C)C=C   1.83  2.452
3                   2-ethylpyrazine              CCc1cnccn1  -5.45 -5.809
4                       heptan-1-ol                CCCCCCCO  -4.21 -2.917

In [21]:
dg = pd.DataFrame({'smiles':df['smiles'].values, 'expt':df['expt'].values})
dg.to_csv(os.path.join(out_dir, "freesolv.csv"), index=False, header=True, encoding="utf8")

## LIPO

In [22]:
df = pd.read_csv(os.path.join(file_dir, "lipo.csv"))
df.head(5)

   CMPD_CHEMBLID   exp                                             smiles
0   CHEMBL596271  3.54            Cn1c(CN2CCN(CC2)c3ccc(Cl)cc3)nc4ccccc14
1  CHEMBL1951080 -1.18  COc1cc(OC)c(cc1NC(=O)CSCC(=O)O)S(=O)(=O)N2C(C)...
2     CHEMBL1771  3.69             COC(=O)[C@@H](N1CCc2sccc2C1)c3ccccc3Cl
3   CHEMBL234951  3.37  OC[C@H](O)CN1C(=O)C(Cc2ccccc12)NC(=O)c3cc4cc(C...
4   CHEMBL565079  3.10  Cc1cccc(C[C@H](NC(=O)c2cc(nn2C)C(C)(C)C)C(=O)N...

In [23]:
dg = pd.DataFrame({'smiles':df['smiles'].values, 'exp':df['exp'].values})
dg.to_csv(os.path.join(out_dir, "lipo.csv"), index=False, header=True, encoding="utf8")

## PDBBIND

In [24]:
df = pd.read_csv(os.path.join(file_dir, "pdbbind.csv"))
df.head(5)

                                    smiles  -logKd/Ki
0           CC(=O)NC(CCC(=O)[O-])C(=O)[O-]       0.40
1  C[NH2+]CCC(Oc1ccc(C(F)(F)F)cc1)c1ccccc1       0.45
2                        CC(=O)N1CCCC(C)C1       0.49
3                     Nc1cccc(C(=O)[O-])c1       0.49
4               CC(=O)Nc1nnc(S(N)(=O)=O)s1       0.60

In [25]:
dg = df.copy(deep=True)
dg.to_csv(os.path.join(out_dir, "pdbbind.csv"), index=False, header=True, encoding="utf8")

## Explore

In [35]:
from rdkit import Chem
def canonicalize_smiles(smiles: str):
    """
    Canonicalize a SMILES using rdkit
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print('Cannot canonicalize SMILES:', smiles)
        return None
    return Chem.MolToSmiles(mol, canonical=True)

In [44]:
dd = pd.read_csv(os.path.join(out_dir, "esol.csv"))
print(len(dd))
dd = dd.drop_duplicates().reset_index(drop=True)
print(len(dd))
dd['canonical_smiles'] = dd['smiles'].apply(lambda x: canonicalize_smiles(x))
dd

1128
1128

,smiles,measured log solubility in mols per litre,canonical_smiles
0,OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)...,-0.770,N#CC(OC1OC(COC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O)c...
1,Cc1occc1C(=O)Nc2ccccc2,-3.300,Cc1occc1C(=O)Nc1ccccc1
2,CC(C)=CCCC(C)=CC(=O),-2.060,CC(C)=CCCC(C)=CC=O
3,c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43,-7.870,c1ccc2c(c1)ccc1c2ccc2c3ccccc3ccc21
4,c1ccsc1,-1.330,c1ccsc1
...,...,...,...
1123,FC(F)(F)C(Cl)Br,-1.710,FC(F)(F)C(Cl)Br
1124,CNC(=O)ON=C(SC)C(=O)N(C)C,0.106,CNC(=O)ON=C(SC)C(=O)N(C)C
1125,CCSCCSP(=S)(OC)OC,-3.091,CCSCCSP(=S)(OC)OC
1126,CCC(C)C,-3.180,CCC(C)C
1127,COP(=O)(OC)OC(=CCl)c1cc(Cl)c(Cl)cc1Cl,-4.522,COP(=O)(OC)OC(=CCl)c1cc(Cl)c(Cl)cc1Cl

In [45]:
dd[dd["canonical_smiles"].duplicated(keep=False)].sort_values("canonical_smiles")

,smiles,measured log solubility in mols per litre,canonical_smiles
222,c1c(Br)ccc2ccccc12,-4.400,Brc1ccc2ccccc2c1
554,Brc1ccc2ccccc2c1,-4.400,Brc1ccc2ccccc2c1
213,CC12CCC(CC1)C(C)(C)O2,-1.640,CC12CCC(CC1)C(C)(C)O2
976,CC12CCC(CC1)C(C)(C)O2,-1.740,CC12CCC(CC1)C(C)(C)O2
232,CC34CCC1C(CCC2CC(O)CCC12C)C3CCC4=O,-4.160,CC12CCC3C(CCC4CC(O)CCC43C)C1CCC2=O
655,CC12CCC(O)CC1CCC3C2CCC4(C)C3CCC4=O,-4.402,CC12CCC3C(CCC4CC(O)CCC43C)C1CCC2=O
825,O=C1NC(=O)NC(=O)C1(CC)C(C)C,-2.148,CCC1(C(C)C)C(=O)NC(=O)NC1=O
701,CCC1(C(C)C)C(=O)NC(=O)NC1=O,-2.210,CCC1(C(C)C)C(=O)NC(=O)NC1=O
147,CCC1(CCC(C)C)C(=O)NC(=O)NC1=O,-2.468,CCC1(CCC(C)C)C(=O)NC(=O)NC1=O
779,O=C1NC(=O)NC(=O)C1(CC)CCC(C)C,-2.658,CCC1(CCC(C)C)C(=O)NC(=O)NC1=O
323,CCC1(C(=O)NC(=O)NC1=O)c2ccccc2,-2.322,CCC1(c2ccccc2)C(=O)NC(=O)NC1=O
465,O=C1NC(=O)NC(=O)C1(CC)c1ccccc1,-2.322,CCC1(c2ccccc2)C(=O)NC(=O)NC1=O
500,CCOP(=S)(OCC)SC(CCl)N2C(=O)c1ccccc1C2=O,-6.340,CCOP(=S)(OCC)SC(CCl)N1C(=O)c2ccccc2C1=O
260,CCOP(=S)(OCC)SC(CCl)N1C(=O)c2ccccc2C1=O,-6.340,CCOP(=S)(OCC)SC(CCl)N1C(=O)c2ccccc2C1=O
680,COc1ccccc1O,-1.960,COc1ccccc1O
1069,COc1ccccc1O,-1.960,COc1ccccc1O
703,Cc1ncc(N(=O)=O)n1CCO,-1.220,Cc1ncc([N+](=O)[O-])n1CCO
822,Cc1ncc(N(=O)=O)n1CCO,-1.260,Cc1ncc([N+](=O)[O-])n1CCO
450,ClC(Cl)C(c1ccc(Cl)cc1)c2ccc(Cl)cc2,-7.200,Clc1ccc(C(c2ccc(Cl)cc2)C(Cl)Cl)cc1
1019,ClC(Cl)C(c1ccc(Cl)cc1)c2ccc(Cl)cc2,-7.200,Clc1ccc(C(c2ccc(Cl)cc2)C(Cl)Cl)cc1
276,OCC(O)C(O)C(O)C(O)CO,1.090,OCC(O)C(O)C(O)C(O)CO
233,OCC(O)C(O)C(O)C(O)CO,0.060,OCC(O)C(O)C(O)C(O)CO

In [54]:
dd.iloc[680,:]

smiles                                       COc1ccccc1O
measured log solubility in mols per litre           -1.96
canonical_smiles                              COc1ccccc1O
Name: 680, dtype: object

In [53]:
dd.iloc[1069,:]

smiles                                       COc1ccccc1O
measured log solubility in mols per litre          -1.96
canonical_smiles                             COc1ccccc1O
Name: 1069, dtype: object

In [52]:
dd.iloc[680,0] == dd.iloc[1069,0]

False

In [55]:
col = "measured log solubility in mols per litre"

dd_avg = (
    dd
    .groupby("canonical_smiles", as_index=False)[col]
    .mean()
)

In [57]:
dd.iloc[]

            canonical_smiles  measured log solubility in mols per litre
0              BrC(Br)(Br)Br                                      -3.14
1                  BrC(Br)Br                                      -1.91
2                      BrCBr                                      -1.17
3                     BrCCBr                                      -1.68
4       Brc1cc(Br)c(Br)cc1Br                                      -6.98
...                      ...                                        ...
1112                 c1ccoc1                                      -0.82
1113                 c1ccsc1                                      -1.33
1114  c1cnc2c(c1)ccc1ncccc12                                      -2.68
1115          c1cnc2ncncc2n1                                       0.02
1116                c1cncnc1                                       1.10

[1117 rows x 2 columns]

In [60]:
import pandas as pd

df_test = pd.DataFrame({
    "smiles": [
        "C(C)O",
        "CCO",
        "CC(=O)O",
        "CC(=O)O",
        "BrC1=CC=CC=C1",
        "c1ccc(Br)cc1"
    ],
    "canonical_smiles": [
        "CCO",              # duplicate
        "CCO",              # duplicate
        "CC(=O)O",          # duplicate
        "CC(=O)O",          # duplicate
        "Brc1ccccc1",       # duplicate
        "Brc1ccccc1"        # duplicate
    ],
    "measured_log_sol": [
        -0.8,
        -1.0,
        -2.1,
        -2.3,
        -4.4,
        -4.6
    ]
})

df_test

          smiles canonical_smiles  measured_log_sol
0          C(C)O              CCO              -0.8
1            CCO              CCO              -1.0
2        CC(=O)O          CC(=O)O              -2.1
3        CC(=O)O          CC(=O)O              -2.3
4  BrC1=CC=CC=C1       Brc1ccccc1              -4.4
5   c1ccc(Br)cc1       Brc1ccccc1              -4.6

In [62]:
col = "measured_log_sol"

dd_avg = (
    df_test
    .groupby("canonical_smiles", as_index=False)[col]
    .mean()
)

dd_avg

  canonical_smiles  measured_log_sol
0       Brc1ccccc1              -4.5
1          CC(=O)O              -2.2
2              CCO              -0.9

In [58]:
dd_avg[dd_avg["canonical_smiles"].duplicated(keep=False)].sort_values("canonical_smiles")

Empty DataFrame
Columns: [canonical_smiles, measured log solubility in mols per litre]
Index: []

In [59]:
dd_avg.sample(10)

,canonical_smiles,measured log solubility in mols per litre
148,CC(C)C(C)C(C)C,-4.80
702,Cc1ccc(N=CN(C)C=Nc2ccc(C)cc2C)c(C)c1,-5.47
826,Clc1cccc(-c2ccccc2)c1,-4.88
752,Cc1nnc2n1-c1ccc(Cl)cc1C(c1ccccc1Cl)=NC2,-4.09
647,COc1cnc2cncnc2n1,-0.91
892,Nc1ccc(Cl)cc1,-1.66
261,CCC(=O)Nc1ccc(Cl)c(Cl)c1,-3.00
878,NC(=S)Nc1ccccc1,-1.77
732,Cc1ccccc1,-2.21
754,Cl/C=C\Cl,-1.30

In [64]:
len(df_test[df_test["canonical_smiles"].duplicated(keep=False)])

6